// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOtU2agUyoemdjCG5ST06iuFKSIWNeqAM',
    appId: '1:340489200051:android:a0aec93a9449e8589eebc6',
    messagingSenderId: '340489200051',
    projectId: 'my-water-flow-app',
    databaseURL: 'https://my-water-flow-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-water-flow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3jGNlKglm7wkq02z19Slmnlq-gyxX80M',
    appId: '1:340489200051:ios:dffc99d425d6b6469eebc6',
    messagingSenderId: '340489200051',
    projectId: 'my-water-flow-app',
    databaseURL: 'https://my-water-flow-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-water-flow-app.firebasestorage.app',
    androidClientId: '340489200051-dc7gdkd8vpdhb9ca2rrj7n12688mktbl.apps.googleusercontent.com',
    iosClientId: '340489200051-9mb1rfr0f1d181mqa4aid4qnr275n5ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.newPro',
  );
}
